# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cd8fc8451ad1d0ef880abb4c1b0b311047af4d861e4c4933577eb9b655b677e9b53631ecc986888162da7c4e563f7e3a4a31abef2d7b8dfb711ce577782e245

test:
  secret_key_base: adcc4cbd16f8ee70a539bd609f8866391299648ebc816ad8d97c81b3d40de03de83df2b5df6bf2ecc5ad46ffd0aea560f7fe9b3fa19d95affbfbfe06e379f413

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
